// traduc.js
window.frasesApp = {
    phrases: [
        { english: "Too many cooks spoil the broth.", spanish: "Muchas manos en la olla echan a perder el caldo." },
        { english: "You can't have your cake and eat it too.", spanish: "No se puede tener el pastel y comérselo también." },
        { english: "That's the way the cookie crumbles.", spanish: "Así se desmorona la galleta." },
        { english: "It's a piece of cake.", spanish: "Es pan comido." },
        { english: "Don't cry over spilled milk.", spanish: "No llores sobre leche derramada." },
        { english: "Bring home the bacon.", spanish: "Llevar el pan a casa." },
        { english: "Spill the beans.", spanish: "Soltar la sopa." },
        { english: "Take it with a grain of salt.", spanish: "Tómalo con un grano de sal." },
        { english: "The proof is in the pudding.", spanish: "La prueba está en el pudín." },
        { english: "Bite off more than you can chew.", spanish: "Morder más de lo que puedes masticar." },
        { english: "In a pickle.", spanish: "En un aprieto." },
        { english: "Cool as a cucumber.", spanish: "Fresco como una lechuga." },
        { english: "Eat like a horse.", spanish: "Comer como un lobo." },
        { english: "Butter someone up.", spanish: "Dar coba a alguien." },
        { english: "The apple of my eye.", spanish: "La niña de mis ojos." },
        { english: "The truth will set you free.", spanish: "La verdad te hará libre." },
        { english: "To tell you the truth, I was surprised.", spanish: "A decir verdad, me sorprendió." },
        { english: "There's some truth in what you say.", spanish: "Hay algo de verdad en lo que dices." },
        { english: "He finally revealed the bitter truth.", spanish: "Finalmente reveló la amarga verdad." },
        { english: "In truth, we never expected this outcome.", spanish: "En verdad, nunca esperábamos este resultado." },
        { english: "Seek the truth and you shall find it.", spanish: "Busca la verdad y la encontrarás." },
        { english: "Goodbye", spanish: "Adiós" },
        { english: "See you later", spanish: "Hasta luego" },
         { english: "The sun rises early in the morning sky.", spanish: "El sol sale temprano en el cielo matutino." },
    { english: "Children play happily in the park every afternoon.", spanish: "Los niños juegan felices en el parque cada tarde." },
    { english: "She reads mystery novels by the fireplace nightly.", spanish: "Ella lee novelas de misterio junto a la chimenea." },
    { english: "Coffee tastes better when shared with good friends.", spanish: "El café sabe mejor cuando se comparte con amigos." },
    { english: "Birds migrate south when winter approaches each year.", spanish: "Las aves migran al sur cuando el invierno se acerca." },
    { english: "Teachers inspire young minds to explore new possibilities.", spanish: "Los maestros inspiran mentes jóvenes a explorar nuevas posibilidades." },
    { english: "Raindrops fell gently on the old wooden roof.", spanish: "Las gotas de lluvia caían suavemente sobre el viejo techo." },
    { english: "We should always appreciate life's simple pleasures daily.", spanish: "Debemos apreciar siempre los pequeños placeres de la vida." },
    { english: "Adventurers discovered ancient ruins deep in the jungle.", spanish: "Aventureros descubrieron ruinas antiguas en lo profundo de la selva." },
    { english: "Music has the power to heal broken hearts.", spanish: "La música tiene el poder de sanar corazones rotos." },
    { english: "Fresh bread baking in the oven smells divine.", spanish: "El pan fresco horneándose en el horno huele divino." },
    { english: "Stars twinkle brightly on clear summer nights above.", spanish: "Las estrellas brillan intensamente en las noches despejadas de verano." },
    { english: "Traveling expands our understanding of different cultures significantly.", spanish: "Viajar amplía nuestro entendimiento de diferentes culturas significativamente." },
    { english: "Kindness costs nothing but means everything to others.", spanish: "La amabilidad no cuesta nada pero lo significa todo." },
    { english: "Books can transport you to imaginary worlds magically.", spanish: "Los libros pueden transportarte a mundos imaginarios mágicamente." },
    { english: "Morning dew glistens on the green grass blades.", spanish: "El rocío matutino brilla sobre las hojas de hierba." },
    { english: "Scientists continue researching solutions for climate change urgently.", spanish: "Los científicos siguen investigando soluciones para el cambio climático." },
    { english: "Laughter echoes through the halls of happy homes.", spanish: "Las risas resuenan en los pasillos de hogares felices." },
    { english: "Memories of childhood stay with us forever vividly.", spanish: "Los recuerdos de la infancia permanecen vívidamente para siempre." },
    { english: "Courage means facing fears even when trembling inside.", spanish: "El coraje implica enfrentar miedos incluso con temblor interno." },
    { english: "Moonlight casts shadows on the quiet desert landscape.", spanish: "La luz lunar proyecta sombras sobre el desierto silencioso." },
    { english: "Curiosity drives humanity to explore unknown territories constantly.", spanish: "La curiosidad impulsa a la humanidad a explorar territorios desconocidos." },
    { english: "Gardening teaches patience through nurturing plants to bloom.", spanish: "La jardinería enseña paciencia al cuidar plantas hasta florecer." },
    { english: "Ocean waves whisper secrets to the sandy shore.", spanish: "Las olas del océano susurran secretos a la orilla." },
    { english: "History reminds us of lessons we must remember.", spanish: "La historia nos recuerda lecciones que debemos recordar." },
    { english: "Artists express emotions through colors and shapes beautifully.", spanish: "Los artistas expresan emociones con colores y formas bellamente." },
    { english: "Winter brings snow-covered landscapes and cozy evenings indoors.", spanish: "El invierno trae paisajes nevados y tardes acogedoras en casa." },
    { english: "Friendship grows stronger with trust and shared experiences.", spanish: "La amistad se fortalece con confianza y experiencias compartidas." },
    { english: "Mountains stand majestically against the vast blue sky.", spanish: "Las montañas se alzan majestuosas contra el vasto cielo azul." },
    { english: "Technology evolves rapidly, changing how we live daily.", spanish: "La tecnología evoluciona rápidamente, cambiando nuestra vida cotidiana." },
    { english: "Cooking requires creativity, passion, and attention to details.", spanish: "Cocinar requiere creatividad, pasión y atención a los detalles." },
    { english: "Dreams give us hope for a better tomorrow.", spanish: "Los sueños nos dan esperanza por un mañana mejor." },
    { english: "Leaves change colors gracefully during autumn before falling.", spanish: "Las hojas cambian de color elegantemente en otoño antes de caer." },
    { english: "Meditation helps calm the mind and reduce stress.", spanish: "La meditación ayuda a calmar la mente y reducir estrés." },
    { english: "Butterflies emerge beautifully from their chrysalis after metamorphosis.", spanish: "Las mariposas emergen bellamente de su crisálida tras la metamorfosis." },
    { english: "Volunteering creates positive impacts in local communities directly.", spanish: "El voluntariado crea impactos positivos directamente en comunidades locales." },
    { english: "Photography captures fleeting moments that become eternal treasures.", spanish: "La fotografía captura momentos fugaces que se vuelven tesoros eternos." },
    { english: "Education empowers individuals to transform their own futures.", spanish: "La educación empodera a individuos para transformar su propio futuro." },
    { english: "Fireflies illuminate summer nights with their magical glow.", spanish: "Las luciérnagas iluminan las noches de verano con su brillo." },
    { english: "Architecture combines art and science in building design.", spanish: "La arquitectura combina arte y ciencia en diseño de edificios." },
    { english: "Journaling helps organize thoughts and document personal growth.", spanish: "Escribir un diario organiza pensamientos y documenta crecimiento personal." },
    { english: "Rainbows appear when sunlight refracts through water droplets.", spanish: "Los arcoíris aparecen cuando la luz se refracta en gotas." },
    { english: "Athletes train rigorously to achieve peak physical performance.", spanish: "Los atletas entrenan rigurosamente para alcanzar máximo rendimiento físico." },
    { english: "Patience is the key to mastering any skill.", spanish: "La paciencia es clave para dominar cualquier habilidad." },
    { english: "Sunsets paint the horizon with breathtaking color palettes.", spanish: "Los atardeceres pintan el horizonte con paletas de colores impresionantes." },
    { english: "Innovation drives progress in every field of study.", spanish: "La innovación impulsa el progreso en cada campo de estudio." },
    { english: "Kind words can brighten someone's day unexpectedly.", spanish: "Palabras amables pueden alegrar el día de alguien inesperadamente." },
    { english: "Time management is essential for achieving personal goals.", spanish: "La gestión del tiempo es esencial para lograr metas personales." },
    { english: "Wildflowers bloom vibrantly along mountain trails each spring.", spanish: "Las flores silvestres florecen vibrantes en senderos montañosos cada primavera." },
    { english: "Museums preserve cultural heritage for future generations.", spanish: "Los museos preservan patrimonio cultural para futuras generaciones." },
    
    { english: "We need to wrap up the meeting by noon.", spanish: "Necesitamos concluir la reunión antes del mediodía." },
    { english: "She always sticks up for her younger brother.", spanish: "Ella siempre defiende a su hermano menor." },
    { english: "They came across an ancient map in the attic.", spanish: "Se toparon con un mapa antiguo en el ático." },
    { english: "Let's bounce ideas off each other tomorrow.", spanish: "Intercambiemos ideas mañana." },
    { english: "He finally fessed up to eating the last cookie.", spanish: "Finalmente confesó haberse comido la última galleta." },
    { english: "The project is starting to pan out well.", spanish: "El proyecto está comenzando a dar buenos resultados." },
    { english: "We should stock up on canned goods.", spanish: "Debemos abastecernos de alimentos enlatados." },
    { english: "The kids were monkeying around with the tools.", spanish: "Los niños estaban jugando con las herramientas." },
    { english: "She ironed out all the contract details.", spanish: "Ella resolvió todos los detalles del contrato." },
    { english: "The smell of smoke put me off my meal.", spanish: "El olor a humo me quitó el apetito." },
    { english: "Let's hash out the schedule over lunch.", spanish: "Acordemos el horario durante el almuerzo." },
    { english: "He kept harping on about the same issue.", spanish: "No paraba de insistir en el mismo tema." },
    { english: "We need to drum up more support.", spanish: "Necesitamos generar más apoyo." },
    { english: "The storm wiped out the power grid.", spanish: "La tormenta dejó fuera de servicio la red eléctrica." },
    { english: "She sized up the competition immediately.", spanish: "Ella evaluó a la competencia de inmediato." },
    { english: "They watered down the original proposal.", spanish: "Suavizaron la propuesta original." },
    { english: "Let's rope in Marco for the presentation.", spanish: "Incluyamos a Marco en la presentación." },
    { english: "The news sent shock waves through the community.", spanish: "La noticia conmocionó a la comunidad." },
    { english: "He chickened out at the last moment.", spanish: "Se echó para atrás en el último momento." },
    { english: "We need to flag down a taxi.", spanish: "Necesitamos detener un taxi." },
    { english: "The team is snowed under with work.", spanish: "El equipo está saturado de trabajo." },
    { english: "She brushed off the negative comments.", spanish: "Ella ignoró los comentarios negativos." },
    { english: "Let's pencil in a date for next week.", spanish: "Agendemos una fecha para la próxima semana." },
    { english: "They fleshed out the story with new details.", spanish: "Desarrollaron la historia con nuevos detalles." },
    { english: "The car broke down on the mountain pass.", spanish: "El auto se averió en el paso montañoso." },
    { english: "He kept zoning out during the lecture.", spanish: "Se quedaba en blanco durante la conferencia." },
    { english: "We should mull over the options first.", spanish: "Deberíamos considerar las opciones primero." },
    { english: "The company is phasing out plastic packaging.", spanish: "La empresa está eliminando gradualmente los envases plásticos." },
    { english: "She nailed down the final agreement.", spanish: "Ella concretó el acuerdo final." },
    { english: "The joke fell flat with the audience.", spanish: "El chiste no causó gracia en el público." },
    { english: "Let's knock off early today.", spanish: "Terminemos temprano hoy." },
    { english: "They papered over the cracks in the system.", spanish: "Ocultaron los defectos del sistema." },
    { english: "The plan is starting to shape up.", spanish: "El plan está empezando a tomar forma." },
    { english: "He talked me into helping with the move.", spanish: "Me convenció de ayudar con la mudanza." },
    { english: "We need to factor in travel expenses.", spanish: "Debemos incluir los gastos de viaje." },
    { english: "The protest sparked off a national debate.", spanish: "La protesta desató un debate nacional." },
    { english: "She wised up to their tricks quickly.", spanish: "Pronto se dio cuenta de sus trucos." },
    { english: "Let's sound out the investors first.", spanish: "Sondeemos primero a los inversionistas." },
    { english: "The deal hinges on the final approval.", spanish: "El trato depende de la aprobación final." },
    { english: "They toned down the aggressive marketing.", spanish: "Suavizaron el marketing agresivo." },
    { english: "He bottled up his emotions for years.", spanish: "Contuvo sus emociones durante años." },
    { english: "The class zeroed in on the key concept.", spanish: "La clase se centró en el concepto clave." },
    { english: "We need to branch out into new markets.", spanish: "Debemos expandirnos a nuevos mercados." },
    { english: "She drummed into us the safety rules.", spanish: "Nos inculcó las normas de seguridad." },
    { english: "The rumors have been floating around.", spanish: "Los rumores han estado circulando." },
    { english: "Let's cave in to their demands this time.", spanish: "Cedamos a sus demandas esta vez." },
    { english: "The team pulled off an amazing victory.", spanish: "El equipo logró una victoria asombrosa." },
    { english: "He glossed over the important details.", spanish: "Pasó por alto los detalles importantes." },
    { english: "We need to lay off temporary workers.", spanish: "Debemos despedir a los trabajadores temporales." },
    { english: "The idea grew on me over time.", spanish: "La idea me fue gustando con el tiempo." },
    { english: "He glossed over the important details.", spanish: "Pasó por alto los detalles importantes." },  
{ english: "We need to lay off temporary workers.", spanish: "Debemos despedir a los trabajadores temporales." },  
{ english: "The idea grew on me over time.", spanish: "La idea me fue gustando con el tiempo." },  
{ english: "They’re scaling back the marketing budget.", spanish: "Están recortando el presupuesto de marketing." },  
{ english: "She’s dropping off the contracts at noon.", spanish: "Ella entregará los contratos al mediodía." },  
{ english: "Let’s hash out the proposal details.", spanish: "Vamos a discutir a fondo los detalles de la propuesta." },  
{ english: "He clocked out early yesterday.", spanish: "Él fichó salida temprano ayer." },  
{ english: "We should nail down the timeline.", spanish: "Deberíamos definir el cronograma." },  
{ english: "The project ate up all our resources.", spanish: "El proyecto consumió todos nuestros recursos." },  
{ english: "She’s gearing up for the audit.", spanish: "Ella se está preparando para la auditoría." },  
{ english: "They brought in an external consultant.", spanish: "Trajeron a un consultor externo." },  
{ english: "Let’s knock off early today.", spanish: "Terminemos temprano hoy." },  
{ english: "He’s stuck with endless paperwork.", spanish: "Él está atascado con papeleo interminable." },  
{ english: "They phased out the legacy system.", spanish: "Eliminaron gradualmente el sistema antiguo." },  
{ english: "She’s weighing up the job offer.", spanish: "Ella está considerando la oferta de trabajo." },  
{ english: "We’re swamped with urgent requests.", spanish: "Estamos saturados de solicitudes urgentes." },  
{ english: "He zoned out during the presentation.", spanish: "Él desconectó durante la presentación." },  
{ english: "Let’s pencil in a brainstorming session.", spanish: "Agendemos una lluvia de ideas." },  
{ english: "They’re ramping up production.", spanish: "Están aumentando la producción." },  
{ english: "The meeting dragged on for hours.", spanish: "La reunión se alargó durante horas." },  
{ english: "She’s sizing up the competition.", spanish: "Ella está evaluando a la competencia." },  
{ english: "We fended off a hostile takeover.", spanish: "Rechazamos una adquisición hostil." },  
{ english: "He’s angling for a promotion.", spanish: "Él está buscando conseguir un ascenso." },  
{ english: "They’re outsourcing IT services.", spanish: "Están externalizando los servicios de TI." },  
{ english: "The CEO signed off on the merger.", spanish: "El CEO aprobó la fusión." },  
{ english: "Let’s touch base before the launch.", spanish: "Coordiemos antes del lanzamiento." },  
{ english: "They’re rolling back the changes.", spanish: "Están revirtiendo los cambios." },  
{ english: "She’s stepping in as interim manager.", spanish: "Ella asumirá como gerente interina." },  
{ english: "We need to drum up new clients.", spanish: "Necesitamos captar nuevos clientes." },  
{ english: "He’s burning through the budget.", spanish: "Él está agotando el presupuesto rápidamente." },  
{ english: "The team pulled off a miracle.", spanish: "El equipo logró un milagro." },  
{ english: "They’re laying out the roadmap.", spanish: "Están delineando el plan de acción." },  
{ english: "She’s bowing out of the project.", spanish: "Ella se está retirando del proyecto." },  
 
{ english: "They’re farming out design work.", spanish: "Están subcontratando el trabajo de diseño." },  
{ english: "He’s gunning for a partnership.", spanish: "Él está buscando convertirse en socio." },  
{ english: "We’re weeding out inefficiencies.", spanish: "Estamos eliminando ineficiencias." },  
{ english: "The CFO signed off on expenditures.", spanish: "El CFO autorizó los gastos." },  
{ english: "She’s taking over the negotiations.", spanish: "Ella se hará cargo de las negociaciones." },  
{ english: "They’re winding down operations.", spanish: "Están reduciendo operaciones gradualmente." },
{ english: "Actions speak louder than words.", spanish: "Las acciones hablan más que las palabras." },
{ english: "The early bird catches the worm.", spanish: "Al que madruga, Dios lo ayuda." },
{ english: "A picture is worth a thousand words.", spanish: "Una imagen vale más que mil palabras." },
{ english: "When in Rome, do as the Romans do.", spanish: "Donde fueres, haz lo que vieres." },
{ english: "The grass is always greener on the other side.", spanish: "La hierba siempre es más verde al otro lado." },
{ english: "Don't count your chickens before they hatch.", spanish: "No cantes victoria antes de tiempo." },
{ english: "You can’t judge a book by its cover.", spanish: "No juzgues un libro por su portada." },
{ english: "Better late than never.", spanish: "Más vale tarde que nunca." },
{ english: "Birds of a feather flock together.", spanish: "Dios los cría y ellos se juntan." },
{ english: "Every cloud has a silver lining.", spanish: "No hay mal que por bien no venga." },
{ english: "Beggars can’t be choosers.", spanish: "A caballo regalado no se le mira el diente." },
{ english: "A watched pot never boils.", spanish: "El que espera, desespera." },
{ english: "Don’t bite the hand that feeds you.", spanish: "No muerdas la mano que te da de comer." },
{ english: "Honesty is the best policy.", spanish: "La honestidad es la mejor política." },
{ english: "Practice makes perfect.", spanish: "La práctica hace al maestro." },
{ english: "Two heads are better than one.", spanish: "Dos cabezas piensan mejor que una." },
{ english: "Easy come, easy go.", spanish: "Lo que fácil viene, fácil se va." },
{ english: "No pain, no gain.", spanish: "Sin esfuerzo no hay recompensa." },
{ english: "Time is money.", spanish: "El tiempo es oro." },
{ english: "Laughter is the best medicine.", spanish: "La risa es la mejor medicina." },
{ english: "Look before you leap.", spanish: "Mira antes de saltar." },
{ english: "Don’t put all your eggs in one basket.", spanish: "No pongas todos los huevos en una sola canasta." },
{ english: "Too many cooks spoil the broth.", spanish: "Muchos cocineros estropean el caldo." },
{ english: "You cant' have your cake and eat it too.", spanish: "No se puede tener todo en la vida." },



{ english: "If it ain`'t broke, don't fix it.", spanish: "Si no está roto, no lo arregles." },
{ english: "Out of sight, out of mind.", spanish: "Ojos que no ven, corazón que no siente." },
{ english: "It takes two to tango.", spanish: "Se necesitan dos para bailar tango." },
{ english: "You reap what you sow.", spanish: "Cosechas lo que siembras." },
{ english: "Under the weather.", spanish: "Estar indispuesto." },
{ english: "Hit the snooze button.", spanish: "Posponer la alarma." },
{ english: "Start the day on the right foot.", spanish: "Empezar el día con buen pie." },
{ english: "Miss the bus.", spanish: "Perder el autobús." },
{ english: "Have a lot on one's plate.", spanish: "Tener mucho entre manos." },
{ english: "Let the dust settle.", spanish: "Dejar que se asiente el polvo." },
{ english: "Run out of steam.", spanish: "Quedarse sin energía." },
{ english: "Break the ice.", spanish: "Romper el hielo." },
{ english: "Spill the beans.", spanish: "Descubrir el pastel." },
{ english: "Jump to conclusions.", spanish: "Sacar conclusiones apresuradas." },
{ english: "Cut corners.", spanish: "Hacer las cosas a medias." },
{ english: "Keep the ball rolling.", spanish: "Mantener el ritmo." },
{ english: "Put out fires.", spanish: "Resolver problemas urgentes." },
{ english: "Go with the flow.", spanish: "Dejarse llevar." },
{ english: "Burn the candle at both ends.", spanish: "Desgastarse por exceso de trabajo." },
{ english: "Hit a snag.", spanish: "Encontrar un obstáculo." },
{ english: "Drop the ball.", spanish: "Fallar en una responsabilidad." },
{ english: "Read between the lines.", spanish: "Captar lo implícito." },
{ english: "Keep one's head above water.", spanish: "Mantenerse a flote." },
{ english: "Catch some Z's.", spanish: "Echar una siesta." },
{ english: "Beat around the bush.", spanish: "Andarse con rodeos." },
{ english: "Tie up loose ends.", spanish: "Atar cabos sueltos." },
{ english: "Go back to the drawing board.", spanish: "Volver a empezar desde cero." },
{ english: "Put all eggs in one basket.", spanish: "Poner todo en un mismo riesgo." },
{ english: "Take a rain check.", spanish: "Dejarlo para otra ocasión." },
{ english: "Bend over backwards.", spanish: "Esforzarse al máximo." },
{ english: "Hit the nail on the head.", spanish: "Dar en el clavo." },
{ english: "Face the music.", spanish: "Afrontar las consecuencias." },
{ english: "Add fuel to the fire.", spanish: "Echar leña al fuego." },
{ english: "Get the ball rolling.", spanish: "Dar el primer paso." },
{ english: "Kill two birds with one stone.", spanish: "Matar dos pájaros de un tiro." },
{ english: "On the same page.", spanish: "Estar en sintonía." },
{ english: "Pull someone's leg.", spanish: "Tomarle el pelo a alguien." },
{ english: "Turn a blind eye.", spanish: "Hacer la vista gorda." },
{ english: "Under the weather.", spanish: "Sentirse indispuesto." },
{ english: "Wear many hats.", spanish: "Asumir múltiples roles." },
{ english: "Pull someone's leg.", spanish: "Tomarle el pelo a alguien." },  
{ english: "Turn a blind eye.", spanish: "Hacer la vista gorda." },  
{ english: "Under the weather.", spanish: "Sentirse indispuesto." },  
{ english: "It was the best of times, it was the worst of times.", spanish: "Era el mejor de los tiempos, era el peor de los tiempos." },  
{ english: "To be or not to be, that is the question.", spanish: "Ser o no ser, esa es la cuestión." },  
{ english: "All animals are equal, but some are more equal than others.", spanish: "Todos los animales son iguales, pero algunos son más iguales que otros." },  
{ english: "So we beat on, boats against the current.", spanish: "Y así seguimos luchando, botes contra la corriente." },  
{ english: "Stay gold, Ponyboy.", spanish: "Mantente dorado, Ponyboy." },  
{ english: "The only way to get rid of a temptation is to yield to it.", spanish: "La única forma de librarse de una tentación es caer en ella." },  
{ english: "Not all those who wander are lost.", spanish: "No todos los que vagan están perdidos." },  
{ english: "I am no bird; and no net ensnares me.", spanish: "No soy un pájaro; y ninguna red me atrapa." },  
{ english: "It is a truth universally acknowledged...", spanish: "Es una verdad universalmente reconocida..." },  
{ english: "The answer to life, the universe, and everything is 42.", spanish: "La respuesta al universo, la vida y todo es 42." },  
{ english: "Call me Ishmael.", spanish: "Llamadme Ismael." },  
{ english: "In the beginning, God created the heavens and the earth.", spanish: "En el principio, Dios creó los cielos y la tierra." },  
{ english: "It is a far, far better thing that I do...", spanish: "Es una meta mucho, mucho mejor la que persigo..." },  
{ english: "You mustn’t be afraid to dream a little bigger.", spanish: "No debes tener miedo de soñar un poco más grande." },  
{ english: "The world is quiet here.", spanish: "El mundo está en silencio aquí." },  
{ english: "We were somewhere around Barstow on the edge of the desert.", spanish: "Estábamos cerca de Barstow, al borde del desierto." },  
{ english: "All happy families are alike; each unhappy family is unhappy in its own way.", spanish: "Todas las familias felices se parecen; las infelices lo son cada una a su manera." },  
{ english: "It was a bright cold day in April, and the clocks were striking thirteen.", spanish: "Era un día frío y brillante de abril, y los relojes daban las trece." },  
{ english: "The man in black fled across the desert, and the gunslinger followed.", spanish: "El hombre de negro huyó a través del desierto, y el pistolero lo siguió." },  
{ english: "The past is a foreign country; they do things differently there.", spanish: "El pasado es un país extranjero; allí hacen las cosas de otro modo." },  
{ english: "It is not down in any map; true places never are.", spanish: "No está en ningún mapa; los lugares verdaderos nunca lo están." },  
{ english: "There is no greater agony than bearing an untold story inside you.", spanish: "No hay agonía más grande que llevar una historia no contada dentro de ti." },  
{ english: "The sky above the port was the color of television, tuned to a dead channel.", spanish: "El cielo sobre el puerto tenía el color de una pantalla de televisor sintonizado a un canal muerto." },  
{ english: "It was a pleasure to burn.", spanish: "Era un placer quemar." },  
{ english: "The sun shone, having no alternative, on the nothing new.", spanish: "El sol brillaba, sin alternativa, sobre la nada nueva." },  
{ english: "You don’t know about me without you have read a book...", spanish: "No sabrías nada de mí si no hubieras leído un libro..." },  
{ english: "The horror! The horror!", spanish: "¡El horror! ¡El horror!" },  
{ english: "They shoot the white girl first.", spanish: "Primero disparan a la chica blanca." },  
{ english: "Once upon a time and a very good time it was...", spanish: "Érase una vez, y un tiempo muy bueno era..." },  
{ english: "The cold passed reluctantly from the earth.", spanish: "El frío abandonó la tierra de mala gana." },  
{ english: "There was a boy called Eustace Clarence Scrubb, and he almost deserved it.", spanish: "Había un niño llamado Eustace Clarence Scrubb, y casi se lo merecía." },  
{ english: "It was a dark and stormy night.", spanish: "Era una noche oscura y tormentosa." },  
{ english: "You better not never tell nobody but God.", spanish: "Más vale que no se lo cuentes a nadie más que a Dios." },  
{ english: "I am an invisible man.", spanish: "Soy un hombre invisible." },  
{ english: "She might arrive late due to the heavy traffic.", spanish: "Podría llegar tarde debido al tráfico pesado." },  
{ english: "This medicine might cause dizziness as a side effect.", spanish: "Este medicamento podría causar mareos como efecto secundario." },  
{ english: "We might cancel the trip if it rains tomorrow.", spanish: "Podríamos cancelar el viaje si llueve mañana." },  
{ english: "I'll call you as soon as I finish the meeting.", spanish: "Te llamaré tan pronto como termine la reunión." },  
{ english: "I'll help you with the project if you need it.", spanish: "Te ayudaré con el proyecto si lo necesitas." },  
{ english: "I'll decide what to wear after checking the weather.", spanish: "Decidiré qué ponerme después de revisar el clima." }, 
{ english: "She might arrive late due to the heavy traffic.", spanish: "Podría llegar tarde debido al tráfico pesado." },  
{ english: "This medicine might cause dizziness as a side effect.", spanish: "Este medicamento podría causar mareos como efecto secundario." },  
{ english: "We might cancel the trip if it rains tomorrow.", spanish: "Podríamos cancelar el viaje si llueve mañana." }, 
{ english: "We must arrive at the airport at least 2 hours before departure.", spanish: "Debemos llegar al aeropuerto al menos 2 horas antes de la salida." },
{ english: "Passengers should check in online to save time.", spanish: "Los pasajeros deberían facturar en línea para ahorrar tiempo." },
{ english: "All liquids must be in containers of 100ml or less.", spanish: "Todos los líquidos deben estar en envases de 100ml o menos." },
{ english: "Boarding usually begins 45 minutes before takeoff.", spanish: "El embarque suele comenzar 45 minutos antes del despegue." },
{ english: "Remember to keep your boarding pass accessible.", spanish: "Recuerda mantener tu tarjeta de embarque accesible." },
{ english: "Electronic devices must be on airplane mode during flight.", spanish: "Los dispositivos electrónicos deben estar en modo avión durante el vuelo." },
{ english: "Flight attendants will demonstrate safety procedures.", spanish: "Los auxiliares de vuelo demostrarán los procedimientos de seguridad." },
{ english: "Turbulence is normal during flights.", spanish: "La turbulencia es normal durante los vuelos." },
{ english: "You can request headphones for in-flight entertainment.", spanish: "Puedes solicitar audífonos para el entretenimiento a bordo." },
{ english: "The seatbelt sign will turn on during landing.", spanish: "La señal de cinturón se encenderá durante el aterrizaje." },
{ english: "Passengers must remain seated until the plane docks.", spanish: "Los pasajeros deben permanecer sentados hasta que el avión esté acoplado." },
{ english: "Baggage claim is located on the lower level.", spanish: "La recogida de equipajes está ubicada en el nivel inferior." },
{ english: "You'll need your passport for international flights.", spanish: "Necesitarás tu pasaporte para vuelos internacionales." },
{ english: "Overhead compartments shouldn't contain heavy items.", spanish: "Los compartimentos superiores no deben contener objetos pesados." },
{ english: "Connecting flights have minimum transfer times.", spanish: "Los vuelos de conexión tienen tiempos mínimos de transferencia." },
{ english: "Delays may occur due to weather conditions.", spanish: "Pueden producirse retrasos debido a condiciones meteorológicas." },
{ english: "Unaccompanied minors require special documentation.", spanish: "Los menores no acompañados requieren documentación especial." },
{ english: "Duty-free shopping is available after security.", spanish: "Las compras libres de impuestos están disponibles después de seguridad." },
{ english: "Priority boarding applies to first class passengers.", spanish: "El embarque prioritario aplica a pasajeros de primera clase." },
{ english: "Luggage weight limits vary by airline.", spanish: "Los límites de peso del equipaje varían según la aerolínea." }, 
{ english: "The end of the world is just the beginning.", spanish: "El fin del mundo es solo el principio." },
 { "english": "Maintain a two-second distance from the vehicle ahead.", "spanish": "Mantén dos segundos de distancia del vehículo adelante." },
  { "english": "Turn on your headlights at dusk or in rain.", "spanish": "Enciende las luces al anochecer o con lluvia." },
  { "english": "Reduce speed when approaching pedestrian crossings.", "spanish": "Reduce la velocidad al acercarte a cruces peatonales." },
  { "english": "Never use your phone while driving.", "spanish": "Nunca uses el teléfono mientras conduces." },
  { "english": "Use the handbrake when parking on slopes.", "spanish": "Usa el freno de mano al estacionar en pendientes." },
  { "english": "Check tire pressure monthly for optimal safety.", "spanish": "Verifica la presión de los neumáticos mensualmente para mayor seguridad." },
  { "english": "Signal at least 30 meters before turning.", "spanish": "Señaliza al menos 30 metros antes de girar." },
  { "english": "Yield to emergency vehicles with sirens on.", "spanish": "Cede el paso a vehículos de emergencia con sirenas activas." },
  { "english": "Stop completely at stop signs, not just slow down.", "spanish": "Detente por completo en señales de alto, no solo reduzcas velocidad." },
  { "english": "You can stay up late as long as you wake up on time tomorrow.", "spanish": "Puedes quedarte despierto hasta tarde siempre que te levantes a tiempo mañana." },
  { "english": "I'll help you as long as you promise to try your best.", "spanish": "Te ayudaré siempre que prometas dar tu mejor esfuerzo." },
  { "english": "This laptop works fine as long as you keep it charged.", "spanish": "Esta laptop funciona bien siempre que la mantengas cargada." },
  { "english": "The beach is beautiful as long as it's not raining.", "spanish": "La playa es hermosa siempre que no esté lloviendo." },
  { "english": "You'll succeed as long as you don't give up.", "spanish": "Tendrás éxito siempre que no te rindas." },
  { "english": "As long as we're together, I'm happy.", "spanish": "Siempre que estemos juntos, soy feliz." },
  { "english": "The soup tastes good as long as you add enough salt.", "spanish": "La sopa sabe bien siempre que le agregues suficiente sal." },
  { "english": "Kids can play here as long as they're supervised.", "spanish": "Los niños pueden jugar aquí siempre que estén supervisados." },
  { "english": "As long as I have my coffee, I can start working.", "spanish": "Siempre que tenga mi café, puedo empezar a trabajar." },
  { "english": "This deal is valid as long as you pay before Friday.", "spanish": "Esta oferta es válida siempre que pagues antes del viernes." },
  { "english": "It took me years to get over you.", "spanish": "Me tomó años superarte." },
{ "english": "She still can't get over you after all this time.", "spanish": "Ella todavía no puede superarte después de todo este tiempo." },
{ "english": "Music helps me get over you.", "spanish": "La música me ayuda a superarte." },
{ "english": "How long will it take to get over you?", "spanish": "¿Cuánto tiempo tomará superarte?" },
{ "english": "I need space to get over you completely.", "spanish": "Necesito espacio para superarte por completo." },
{ "english": "It's just a joke, get over it!", "spanish": "Es solo una broma, ¡supéralo!" },
{ "english": "You lost the game, get over it.", "spanish": "Perdiste el juego, acéptalo." },
{ "english": "Life isn't fair - get over it and move on.", "spanish": "La vida no es justa - acéptalo y sigue adelante." },
{ "english": "He needs to get over his fear of flying.", "spanish": "Él necesita superar su miedo a volar." },
{ "english": "Get over it already, it happened months ago.", "spanish": "Supéralo ya, sucedió hace meses." },
{ "english": "True greatness requires humility.", "spanish": "La verdadera grandeza requiere humildad." },
{ "english": "She accepted the award with genuine humility.", "spanish": "Ella aceptó el premio con genuina humildad." },
{ "english": "Humility is the foundation of wisdom.", "spanish": "La humildad es la base de la sabiduría." },
{ "english": "His humility despite his success is admirable.", "spanish": "Su humildad a pesar de su éxito es admirable." },
{ "english": "Learn to speak with humility and respect.", "spanish": "Aprende a hablar con humildad y respeto." },

  
  {
    "english": "She poured the milk into the cup carefully.",
    "spanish": "Ella vertió la leche en la taza con cuidado."
  },
  {
    "english": "The magician turned the rabbit into a dove.",
    "spanish": "El mago transformó el conejo en una paloma."
  },
  {
    "english": "We need to look into this problem immediately.",
    "spanish": "Necesitamos investigar este problema inmediatamente."
  },
  {
    "english": "He accidentally bumped into the glass door.",
    "spanish": "Él accidentalmente chocó contra la puerta de vidrio."
  },
  {
    "english": "The caterpillar will transform into a butterfly.",
    "spanish": "La oruga se transformará en mariposa."
  },
  {
    "english": "She translated the book into three languages.",
    "spanish": "Ella tradujo el libro a tres idiomas."
  },
  {
    "english": "They broke into the old mansion at midnight.",
    "spanish": "Ellos irrumpieron en la mansión antigua a medianoche."
  },
  {
    "english": "The river flows into the ocean near here.",
    "spanish": "El río desemboca en el océano cerca de aquí."
  },
  {
    "english": "He talked himself into buying the expensive car.",
    "spanish": "Él se convenció a sí mismo de comprar el auto caro."
  },
  {
    "english": "The children jumped into the pool with excitement.",
    "spanish": "Los niños saltaron a la piscina con emoción."
  },


{ english: "The truth will set you free.", spanish: "La verdad te hará libre." },
{ english: "To tell you the truth, I was surprised.", spanish: "A decir verdad, me sorprendió." },
{ english: "There's some truth in what you say.", spanish: "Hay algo de verdad en lo que dices." },
{ english: "He finally revealed the bitter truth.", spanish: "Finalmente reveló la amarga verdad." },
{ english: "In truth, we never expected this outcome.", spanish: "En verdad, nunca esperábamos este resultado." },
{ english: "Seek the truth and you shall find it.", spanish: "Busca la verdad y la encontrarás." },
{ english: "Too many cooks spoil the broth.", spanish: "Muchas manos en la olla echan a perder el caldo." },
{ english: "You can't have your cake and eat it too.", spanish: "No se puede tener el pastel y comérselo también." },
{ english: "That's the way the cookie crumbles.", spanish: "Así se desmorona la galleta." },
{ english: "It's a piece of cake.", spanish: "Es pan comido." },
{ english: "They are pulling out all the stops to finish the project on time.", spanish: "Están haciendo todo lo posible para terminar el proyecto a tiempo." },
{ english: "The dentist had no choice but to start pulling out the patient's tooth.", spanish: "El dentista no tuvo más remedio que empezar a sacar el diente del paciente." },
{ english: "We're pulling out of the driveway right now; we'll be there in a minute.", spanish: "Estamos saliendo de la entrada del coche ahora mismo; estaremos allí en un minuto." },
{ english: "After years of fighting, the troops are finally pulling out of the country.", spanish: "Después de años de lucha, las tropas finalmente se están retirando del país." },
{ english: "She's pulling out her credit card to pay for the groceries.", spanish: "Ella está sacando su tarjeta de crédito para pagar la compra." },
{ english: "I saw him pulling out some weeds from the garden this morning.", spanish: "Lo vi arrancando algunas malas hierbas del jardín esta mañana." },
{ english: "The company announced it will be pulling out of the European market next year.", spanish: "La empresa anunció que se retirará del mercado europeo el año que viene." },
{ english: "He was pulling out a handkerchief from his pocket to wipe his eyes.", spanish: "Estaba sacando un pañuelo de su bolsillo para secarse los ojos." },
{ english: "The magician was pulling out a rabbit from his hat.", spanish: "El mago estaba sacando un conejo de su sombrero." },
{ english: "He made a quick decision, pulling out of the deal at the last minute.", spanish: "Tomó una decisión rápida, retirándose del trato en el último minuto." },
{ english: "The train is pulling out of the station in ten minutes.", spanish: "El tren está saliendo de la estación en diez minutos." },
{ english: "They were pulling out old photos from the attic.", spanish: "Estaban sacando fotos antiguas del ático." },
{ english: "The doctor recommended pulling out the wisdom tooth because it was causing problems.", spanish: "El médico recomendó extraer la muela del juicio porque estaba causando problemas." },
{ english: "It was a difficult negotiation, but we ended up pulling out a good deal.", spanish: "Fue una negociación difícil, pero al final conseguimos un buen trato." },
{ english: "I saw the pilot pulling out the landing gear as we approached the runway.", spanish: "Vi al piloto sacar el tren de aterrizaje mientras nos acercábamos a la pista." },
{ english: "She's always pulling out her phone to take pictures of her food.", spanish: "Siempre está sacando su teléfono para tomar fotos de su comida." },
{ english: "The military will be pulling out its forces from the region soon.", spanish: "El ejército retirará sus fuerzas de la región pronto." },
{ english: "He was pulling out of the race due to an injury.", spanish: "Se estaba retirando de la carrera debido a una lesión." },
{ english: "The government is pulling out of the international treaty.", spanish: "El gobierno se está retirando del tratado internacional." },
{ english: "We're pulling out all the stops to make sure the event is a success.", spanish: "Estamos haciendo todo lo posible para asegurarnos de que el evento sea un éxito." },

{ english: "Bring home the bacon.", spanish: "Llevar el pan a casa." },
{ english: "Spill the beans.", spanish: "Soltar la sopa." },
{ english: "Take it with a grain of salt.", spanish: "Tómalo con un grano de sal." },
{ english: "The proof is in the pudding.", spanish: "La prueba está en el pudín." },
{ english: "Bite off more than you can chew.", spanish: "Morder más de lo que puedes masticar." },
{ english: "In a pickle.", spanish: "En un aprieto." },
{ english: "Cool as a cucumber.", spanish: "Fresco como una lechuga." },

 { english: "The sun rises early in the morning sky.", spanish: "El sol sale temprano en el cielo matutino." },
    { english: "Children play happily in the park every afternoon.", spanish: "Los niños juegan felices en el parque cada tarde." },
    { english: "She reads mystery novels by the fireplace nightly.", spanish: "Ella lee novelas de misterio junto a la chimenea." },
    { english: "Coffee tastes better when shared with good friends.", spanish: "El café sabe mejor cuando se comparte con amigos." },
    { english: "Birds migrate south when winter approaches each year.", spanish: "Las aves migran al sur cuando el invierno se acerca." },
    { english: "Teachers inspire young minds to explore new possibilities.", spanish: "Los maestros inspiran mentes jóvenes a explorar nuevas posibilidades." },
    { english: "Raindrops fell gently on the old wooden roof.", spanish: "Las gotas de lluvia caían suavemente sobre el viejo techo." },
    { english: "We should always appreciate life's simple pleasures daily.", spanish: "Debemos apreciar siempre los pequeños placeres de la vida." },
    { english: "Adventurers discovered ancient ruins deep in the jungle.", spanish: "Aventureros descubrieron ruinas antiguas en lo profundo de la selva." },
    { english: "Music has the power to heal broken hearts.", spanish: "La música tiene el poder de sanar corazones rotos." },
    { english: "Fresh bread baking in the oven smells divine.", spanish: "El pan fresco horneándose en el horno huele divino." },
    { english: "Stars twinkle brightly on clear summer nights above.", spanish: "Las estrellas brillan intensamente en las noches despejadas de verano." },
    { english: "Traveling expands our understanding of different cultures significantly.", spanish: "Viajar amplía nuestro entendimiento de diferentes culturas significativamente." },
    { english: "Kindness costs nothing but means everything to others.", spanish: "La amabilidad no cuesta nada pero lo significa todo." },
    { english: "Books can transport you to imaginary worlds magically.", spanish: "Los libros pueden transportarte a mundos imaginarios mágicamente." },
    { english: "Morning dew glistens on the green grass blades.", spanish: "El rocío matutino brilla sobre las hojas de hierba." },
    { english: "Scientists continue researching solutions for climate change urgently.", spanish: "Los científicos siguen investigando soluciones para el cambio climático." },
    { english: "Laughter echoes through the halls of happy homes.", spanish: "Las risas resuenan en los pasillos de hogares felices." },
    { english: "Memories of childhood stay with us forever vividly.", spanish: "Los recuerdos de la infancia permanecen vívidamente para siempre." },
    { english: "Courage means facing fears even when trembling inside.", spanish: "El coraje implica enfrentar miedos incluso con temblor interno." },
    { english: "Moonlight casts shadows on the quiet desert landscape.", spanish: "La luz lunar proyecta sombras sobre el desierto silencioso." },
    { english: "Curiosity drives humanity to explore unknown territories constantly.", spanish: "La curiosidad impulsa a la humanidad a explorar territorios desconocidos." },
    { english: "Gardening teaches patience through nurturing plants to bloom.", spanish: "La jardinería enseña paciencia al cuidar plantas hasta florecer." },
    { english: "Ocean waves whisper secrets to the sandy shore.", spanish: "Las olas del océano susurran secretos a la orilla." },
    { english: "History reminds us of lessons we must remember.", spanish: "La historia nos recuerda lecciones que debemos recordar." },
    { english: "Artists express emotions through colors and shapes beautifully.", spanish: "Los artistas expresan emociones con colores y formas bellamente." },
    { english: "Winter brings snow-covered landscapes and cozy evenings indoors.", spanish: "El invierno trae paisajes nevados y tardes acogedoras en casa." },
    { english: "Friendship grows stronger with trust and shared experiences.", spanish: "La amistad se fortalece con confianza y experiencias compartidas." },
    { english: "Mountains stand majestically against the vast blue sky.", spanish: "Las montañas se alzan majestuosas contra el vasto cielo azul." },
    { english: "Technology evolves rapidly, changing how we live daily.", spanish: "La tecnología evoluciona rápidamente, cambiando nuestra vida cotidiana." },
    { english: "Cooking requires creativity, passion, and attention to details.", spanish: "Cocinar requiere creatividad, pasión y atención a los detalles." },
    { english: "Dreams give us hope for a better tomorrow.", spanish: "Los sueños nos dan esperanza por un mañana mejor." },
    { english: "Leaves change colors gracefully during autumn before falling.", spanish: "Las hojas cambian de color elegantemente en otoño antes de caer." },
    { english: "Meditation helps calm the mind and reduce stress.", spanish: "La meditación ayuda a calmar la mente y reducir estrés." },
    { english: "Butterflies emerge beautifully from their chrysalis after metamorphosis.", spanish: "Las mariposas emergen bellamente de su crisálida tras la metamorfosis." },
    { english: "Volunteering creates positive impacts in local communities directly.", spanish: "El voluntariado crea impactos positivos directamente en comunidades locales." },
    { english: "Photography captures fleeting moments that become eternal treasures.", spanish: "La fotografía captura momentos fugaces que se vuelven tesoros eternos." },
    { english: "Education empowers individuals to transform their own futures.", spanish: "La educación empodera a individuos para transformar su propio futuro." },
    { english: "Fireflies illuminate summer nights with their magical glow.", spanish: "Las luciérnagas iluminan las noches de verano con su brillo." },
    { english: "Architecture combines art and science in building design.", spanish: "La arquitectura combina arte y ciencia en diseño de edificios." },
    { english: "Journaling helps organize thoughts and document personal growth.", spanish: "Escribir un diario organiza pensamientos y documenta crecimiento personal." },
    { english: "Rainbows appear when sunlight refracts through water droplets.", spanish: "Los arcoíris aparecen cuando la luz se refracta en gotas." },
    { english: "Athletes train rigorously to achieve peak physical performance.", spanish: "Los atletas entrenan rigurosamente para alcanzar máximo rendimiento físico." },
    { english: "Patience is the key to mastering any skill.", spanish: "La paciencia es clave para dominar cualquier habilidad." },
    { english: "Sunsets paint the horizon with breathtaking color palettes.", spanish: "Los atardeceres pintan el horizonte con paletas de colores impresionantes." },
    { english: "Innovation drives progress in every field of study.", spanish: "La innovación impulsa el progreso en cada campo de estudio." },
    { english: "Kind words can brighten someone's day unexpectedly.", spanish: "Palabras amables pueden alegrar el día de alguien inesperadamente." },
    { english: "Time management is essential for achieving personal goals.", spanish: "La gestión del tiempo es esencial para lograr metas personales." },
    { english: "Wildflowers bloom vibrantly along mountain trails each spring.", spanish: "Las flores silvestres florecen vibrantes en senderos montañosos cada primavera." },
    { english: "Museums preserve cultural heritage for future generations.", spanish: "Los museos preservan patrimonio cultural para futuras generaciones." },
    
    { english: "We need to wrap up the meeting by noon.", spanish: "Necesitamos concluir la reunión antes del mediodía." },
    { english: "She always sticks up for her younger brother.", spanish: "Ella siempre defiende a su hermano menor." },
    { english: "They came across an ancient map in the attic.", spanish: "Se toparon con un mapa antiguo en el ático." },
    { english: "Let's bounce ideas off each other tomorrow.", spanish: "Intercambiemos ideas mañana." },
    { english: "He finally fessed up to eating the last cookie.", spanish: "Finalmente confesó haberse comido la última galleta." },
    { english: "The project is starting to pan out well.", spanish: "El proyecto está comenzando a dar buenos resultados." },
    { english: "We should stock up on canned goods.", spanish: "Debemos abastecernos de alimentos enlatados." },
    { english: "The kids were monkeying around with the tools.", spanish: "Los niños estaban jugando con las herramientas." },
    { english: "She ironed out all the contract details.", spanish: "Ella resolvió todos los detalles del contrato." },
    { english: "The smell of smoke put me off my meal.", spanish: "El olor a humo me quitó el apetito." },
    { english: "Let's hash out the schedule over lunch.", spanish: "Acordemos el horario durante el almuerzo." },
    { english: "He kept harping on about the same issue.", spanish: "No paraba de insistir en el mismo tema." },
    { english: "We need to drum up more support.", spanish: "Necesitamos generar más apoyo." },
    { english: "The storm wiped out the power grid.", spanish: "La tormenta dejó fuera de servicio la red eléctrica." },
    { english: "She sized up the competition immediately.", spanish: "Ella evaluó a la competencia de inmediato." },
    { english: "They watered down the original proposal.", spanish: "Suavizaron la propuesta original." },
    { english: "Let's rope in Marco for the presentation.", spanish: "Incluyamos a Marco en la presentación." },
    { english: "The news sent shock waves through the community.", spanish: "La noticia conmocionó a la comunidad." },
    { english: "He chickened out at the last moment.", spanish: "Se echó para atrás en el último momento." },
    { english: "We need to flag down a taxi.", spanish: "Necesitamos detener un taxi." },
    { english: "The team is snowed under with work.", spanish: "El equipo está saturado de trabajo." },
    { english: "She brushed off the negative comments.", spanish: "Ella ignoró los comentarios negativos." },
    { english: "Let's pencil in a date for next week.", spanish: "Agendemos una fecha para la próxima semana." },
    { english: "They fleshed out the story with new details.", spanish: "Desarrollaron la historia con nuevos detalles." },
    { english: "The car broke down on the mountain pass.", spanish: "El auto se averió en el paso montañoso." },
    { english: "He kept zoning out during the lecture.", spanish: "Se quedaba en blanco durante la conferencia." },
    { english: "We should mull over the options first.", spanish: "Deberíamos considerar las opciones primero." },
    { english: "The company is phasing out plastic packaging.", spanish: "La empresa está eliminando gradualmente los envases plásticos." },
    { english: "She nailed down the final agreement.", spanish: "Ella concretó el acuerdo final." },
    { english: "The joke fell flat with the audience.", spanish: "El chiste no causó gracia en el público." },
    { english: "Let's knock off early today.", spanish: "Terminemos temprano hoy." },
    { english: "They papered over the cracks in the system.", spanish: "Ocultaron los defectos del sistema." },
    { english: "The plan is starting to shape up.", spanish: "El plan está empezando a tomar forma." },
    { english: "He talked me into helping with the move.", spanish: "Me convenció de ayudar con la mudanza." },
    { english: "We need to factor in travel expenses.", spanish: "Debemos incluir los gastos de viaje." },
    { english: "The protest sparked off a national debate.", spanish: "La protesta desató un debate nacional." },
    { english: "She wised up to their tricks quickly.", spanish: "Pronto se dio cuenta de sus trucos." },
    { english: "Let's sound out the investors first.", spanish: "Sondeemos primero a los inversionistas." },
    { english: "The deal hinges on the final approval.", spanish: "El trato depende de la aprobación final." },
    { english: "They toned down the aggressive marketing.", spanish: "Suavizaron el marketing agresivo." },
    { english: "He bottled up his emotions for years.", spanish: "Contuvo sus emociones durante años." },
    { english: "The class zeroed in on the key concept.", spanish: "La clase se centró en el concepto clave." },
    { english: "We need to branch out into new markets.", spanish: "Debemos expandirnos a nuevos mercados." },
    { english: "She drummed into us the safety rules.", spanish: "Nos inculcó las normas de seguridad." },
    { english: "The rumors have been floating around.", spanish: "Los rumores han estado circulando." },
    { english: "Let's cave in to their demands this time.", spanish: "Cedamos a sus demandas esta vez." },
    { english: "The team pulled off an amazing victory.", spanish: "El equipo logró una victoria asombrosa." },
    { english: "He glossed over the important details.", spanish: "Pasó por alto los detalles importantes." },
    { english: "We need to lay off temporary workers.", spanish: "Debemos despedir a los trabajadores temporales." },
    { english: "The idea grew on me over time.", spanish: "La idea me fue gustando con el tiempo." },
    { english: "He glossed over the important details.", spanish: "Pasó por alto los detalles importantes." },  
{ english: "We need to lay off temporary workers.", spanish: "Debemos despedir a los trabajadores temporales." },  
{ english: "The idea grew on me over time.", spanish: "La idea me fue gustando con el tiempo." },  
{ english: "They’re scaling back the marketing budget.", spanish: "Están recortando el presupuesto de marketing." },  
{ english: "She’s dropping off the contracts at noon.", spanish: "Ella entregará los contratos al mediodía." },  
{ english: "Let’s hash out the proposal details.", spanish: "Vamos a discutir a fondo los detalles de la propuesta." },  
{ english: "He clocked out early yesterday.", spanish: "Él fichó salida temprano ayer." },  
{ english: "We should nail down the timeline.", spanish: "Deberíamos definir el cronograma." },  
{ english: "The project ate up all our resources.", spanish: "El proyecto consumió todos nuestros recursos." },  
{ english: "She’s gearing up for the audit.", spanish: "Ella se está preparando para la auditoría." },  
{ english: "They brought in an external consultant.", spanish: "Trajeron a un consultor externo." },  
{ english: "Let’s knock off early today.", spanish: "Terminemos temprano hoy." },  
{ english: "He’s stuck with endless paperwork.", spanish: "Él está atascado con papeleo interminable." },  
{ english: "They phased out the legacy system.", spanish: "Eliminaron gradualmente el sistema antiguo." },  
{ english: "She’s weighing up the job offer.", spanish: "Ella está considerando la oferta de trabajo." },  
{ english: "We’re swamped with urgent requests.", spanish: "Estamos saturados de solicitudes urgentes." },  
{ english: "He zoned out during the presentation.", spanish: "Él desconectó durante la presentación." },  
{ english: "Let’s pencil in a brainstorming session.", spanish: "Agendemos una lluvia de ideas." },  
{ english: "They’re ramping up production.", spanish: "Están aumentando la producción." },  
{ english: "The meeting dragged on for hours.", spanish: "La reunión se alargó durante horas." },  
{ english: "She’s sizing up the competition.", spanish: "Ella está evaluando a la competencia." },  
{ english: "We fended off a hostile takeover.", spanish: "Rechazamos una adquisición hostil." },  
{ english: "He’s angling for a promotion.", spanish: "Él está buscando conseguir un ascenso." },  
{ english: "They’re outsourcing IT services.", spanish: "Están externalizando los servicios de TI." },  
{ english: "The CEO signed off on the merger.", spanish: "El CEO aprobó la fusión." },  
{ english: "Let’s touch base before the launch.", spanish: "Coordiemos antes del lanzamiento." },  
{ english: "They’re rolling back the changes.", spanish: "Están revirtiendo los cambios." },  
{ english: "She’s stepping in as interim manager.", spanish: "Ella asumirá como gerente interina." },  
{ english: "We need to drum up new clients.", spanish: "Necesitamos captar nuevos clientes." },  
{ english: "He’s burning through the budget.", spanish: "Él está agotando el presupuesto rápidamente." },  
{ english: "The team pulled off a miracle.", spanish: "El equipo logró un milagro." },  
{ english: "They’re laying out the roadmap.", spanish: "Están delineando el plan de acción." },  
{ english: "She’s bowing out of the project.", spanish: "Ella se está retirando del proyecto." },  
 
{ english: "They’re farming out design work.", spanish: "Están subcontratando el trabajo de diseño." },  
{ english: "He’s gunning for a partnership.", spanish: "Él está buscando convertirse en socio." },  
{ english: "We’re weeding out inefficiencies.", spanish: "Estamos eliminando ineficiencias." },  
{ english: "The CFO signed off on expenditures.", spanish: "El CFO autorizó los gastos." },  
{ english: "She’s taking over the negotiations.", spanish: "Ella se hará cargo de las negociaciones." },  
{ english: "They’re winding down operations.", spanish: "Están reduciendo operaciones gradualmente." },
{ english: "Actions speak louder than words.", spanish: "Las acciones hablan más que las palabras." },
{ english: "The early bird catches the worm.", spanish: "Al que madruga, Dios lo ayuda." },
{ english: "A picture is worth a thousand words.", spanish: "Una imagen vale más que mil palabras." },
{ english: "When in Rome, do as the Romans do.", spanish: "Donde fueres, haz lo que vieres." },
{ english: "The grass is always greener on the other side.", spanish: "La hierba siempre es más verde al otro lado." },
{ english: "Don't count your chickens before they hatch.", spanish: "No cantes victoria antes de tiempo." },
{ english: "You can’t judge a book by its cover.", spanish: "No juzgues un libro por su portada." },
{ english: "Better late than never.", spanish: "Más vale tarde que nunca." },
{ english: "Birds of a feather flock together.", spanish: "Dios los cría y ellos se juntan." },
{ english: "Every cloud has a silver lining.", spanish: "No hay mal que por bien no venga." },
{ english: "Beggars can’t be choosers.", spanish: "A caballo regalado no se le mira el diente." },
{ english: "A watched pot never boils.", spanish: "El que espera, desespera." },
{ english: "Don’t bite the hand that feeds you.", spanish: "No muerdas la mano que te da de comer." },
{ english: "Honesty is the best policy.", spanish: "La honestidad es la mejor política." },
{ english: "Practice makes perfect.", spanish: "La práctica hace al maestro." },
{ english: "Two heads are better than one.", spanish: "Dos cabezas piensan mejor que una." },
{ english: "Easy come, easy go.", spanish: "Lo que fácil viene, fácil se va." },
{ english: "No pain, no gain.", spanish: "Sin esfuerzo no hay recompensa." },
{ english: "Time is money.", spanish: "El tiempo es oro." },
{ english: "Laughter is the best medicine.", spanish: "La risa es la mejor medicina." },
{ english: "You cant' have your cake and eat it too.", spanish: "No se puede tener todo en la vida." },
{ english: "Let sleeping dogs lie.", spanish: "Deja que el perro duerma." },
{ english: "Rome wasn’t built in a day.", spanish: "Roma no se construyó en un día." },
{ english: "A penny saved is a penny earned.", spanish: "Un centavo ahorrado es un centavo ganado." },



{ english: "Throw in the towel.", spanish: "Tirar la toalla." },
{ english: "Under the weather.", spanish: "Estar indispuesto." },
{ english: "Hit the snooze button.", spanish: "Posponer la alarma." },
{ english: "Start the day on the right foot.", spanish: "Empezar el día con buen pie." },
{ english: "Miss the bus.", spanish: "Perder el autobús." },
{ english: "Have a lot on one's plate.", spanish: "Tener mucho entre manos." },
{ english: "Let the dust settle.", spanish: "Dejar que se asiente el polvo." },
{ english: "Run out of steam.", spanish: "Quedarse sin energía." },

{ english: "Jump to conclusions.", spanish: "Sacar conclusiones apresuradas." },
{ english: "Cut corners.", spanish: "Hacer las cosas a medias." },
{ english: "Keep the ball rolling.", spanish: "Mantener el ritmo." },
{ english: "Put out fires.", spanish: "Resolver problemas urgentes." },
{ english: "Go with the flow.", spanish: "Dejarse llevar." },
{ english: "Burn the candle at both ends.", spanish: "Desgastarse por exceso de trabajo." },
{ english: "Hit a snag.", spanish: "Encontrar un obstáculo." },
{ english: "Drop the ball.", spanish: "Fallar en una responsabilidad." },
{ english: "Read between the lines.", spanish: "Captar lo implícito." },
{ english: "Keep one's head above water.", spanish: "Mantenerse a flote." },
{ english: "Catch some Z's.", spanish: "Echar una siesta." },
{ english: "Beat around the bush.", spanish: "Andarse con rodeos." },
{ english: "Tie up loose ends.", spanish: "Atar cabos sueltos." },
{ english: "Go back to the drawing board.", spanish: "Volver a empezar desde cero." },
{ english: "Put all eggs in one basket.", spanish: "Poner todo en un mismo riesgo." },
{ english: "Take a rain check.", spanish: "Dejarlo para otra ocasión." },
{ english: "Bend over backwards.", spanish: "Esforzarse al máximo." },
{ english: "Hit the nail on the head.", spanish: "Dar en el clavo." },
{ english: "Face the music.", spanish: "Afrontar las consecuencias." },
{ english: "The answer to life, the universe, and everything is 42.", spanish: "La respuesta al universo, la vida y todo es 42." },  
{ english: "Call me Ishmael.", spanish: "Llamadme Ismael." },  
{ english: "In the beginning, God created the heavens and the earth.", spanish: "En el principio, Dios creó los cielos y la tierra." },  
{ english: "It is a far, far better thing that I do...", spanish: "Es una meta mucho, mucho mejor la que persigo..." },  
{ english: "You mustn’t be afraid to dream a little bigger.", spanish: "No debes tener miedo de soñar un poco más grande." },  
{ english: "The world is quiet here.", spanish: "El mundo está en silencio aquí." },  
{ english: "We were somewhere around Barstow on the edge of the desert.", spanish: "Estábamos cerca de Barstow, al borde del desierto." },  
{ english: "All happy families are alike; each unhappy family is unhappy in its own way.", spanish: "Todas las familias felices se parecen; las infelices lo son cada una a su manera." },  
{ english: "It was a bright cold day in April, and the clocks were striking thirteen.", spanish: "Era un día frío y brillante de abril, y los relojes daban las trece." },  
{ english: "The man in black fled across the desert, and the gunslinger followed.", spanish: "El hombre de negro huyó a través del desierto, y el pistolero lo siguió." },  
{ english: "The past is a foreign country; they do things differently there.", spanish: "El pasado es un país extranjero; allí hacen las cosas de otro modo." },  
{ english: "It is not down in any map; true places never are.", spanish: "No está en ningún mapa; los lugares verdaderos nunca lo están." },  
{ english: "There is no greater agony than bearing an untold story inside you.", spanish: "No hay agonía más grande que llevar una historia no contada dentro de ti." },  
{ english: "The sky above the port was the color of television, tuned to a dead channel.", spanish: "El cielo sobre el puerto tenía el color de una pantalla de televisor sintonizado a un canal muerto." },  
{ english: "It was a pleasure to burn.", spanish: "Era un placer quemar." },  
{ english: "The sun shone, having no alternative, on the nothing new.", spanish: "El sol brillaba, sin alternativa, sobre la nada nueva." },  
{ english: "You don’t know about me without you have read a book...", spanish: "No sabrías nada de mí si no hubieras leído un libro..." },  
{ english: "The horror! The horror!", spanish: "¡El horror! ¡El horror!" },  
{ english: "They shoot the white girl first.", spanish: "Primero disparan a la chica blanca." },  
{ english: "Once upon a time and a very good time it was...", spanish: "Érase una vez, y un tiempo muy bueno era..." },  
{ english: "The cold passed reluctantly from the earth.", spanish: "El frío abandonó la tierra de mala gana." },  
{ english: "There was a boy called Eustace Clarence Scrubb, and he almost deserved it.", spanish: "Había un niño llamado Eustace Clarence Scrubb, y casi se lo merecía." },  
{ english: "It was a dark and stormy night.", spanish: "Era una noche oscura y tormentosa." },  
{ english: "You better not never tell nobody but God.", spanish: "Más vale que no se lo cuentes a nadie más que a Dios." },  
{ english: "I am an invisible man.", spanish: "Soy un hombre invisible." },  
{ english: "She might arrive late due to the heavy traffic.", spanish: "Podría llegar tarde debido al tráfico pesado." },  
{ english: "This medicine might cause dizziness as a side effect.", spanish: "Este medicamento podría causar mareos como efecto secundario." },  
{ english: "We might cancel the trip if it rains tomorrow.", spanish: "Podríamos cancelar el viaje si llueve mañana." },  
{ english: "I'll call you as soon as I finish the meeting.", spanish: "Te llamaré tan pronto como termine la reunión." },  
{ english: "I'll help you with the project if you need it.", spanish: "Te ayudaré con el proyecto si lo necesitas." },  
{ english: "I'll decide what to wear after checking the weather.", spanish: "Decidiré qué ponerme después de revisar el clima." }, 
{ english: "She might arrive late due to the heavy traffic.", spanish: "Podría llegar tarde debido al tráfico pesado." },  
{ english: "This medicine might cause dizziness as a side effect.", spanish: "Este medicamento podría causar mareos como efecto secundario." },  
{ english: "We might cancel the trip if it rains tomorrow.", spanish: "Podríamos cancelar el viaje si llueve mañana." }, 
{ english: "We must arrive at the airport at least 2 hours before departure.", spanish: "Debemos llegar al aeropuerto al menos 2 horas antes de la salida." },
{ english: "Passengers should check in online to save time.", spanish: "Los pasajeros deberían facturar en línea para ahorrar tiempo." },
{ english: "All liquids must be in containers of 100ml or less.", spanish: "Todos los líquidos deben estar en envases de 100ml o menos." },
{ english: "Boarding usually begins 45 minutes before takeoff.", spanish: "El embarque suele comenzar 45 minutos antes del despegue." },
{ english: "Remember to keep your boarding pass accessible.", spanish: "Recuerda mantener tu tarjeta de embarque accesible." },
{ english: "Electronic devices must be on airplane mode during flight.", spanish: "Los dispositivos electrónicos deben estar en modo avión durante el vuelo." },
{ english: "Flight attendants will demonstrate safety procedures.", spanish: "Los auxiliares de vuelo demostrarán los procedimientos de seguridad." },
{ english: "Turbulence is normal during flights.", spanish: "La turbulencia es normal durante los vuelos." },
{ english: "You can request headphones for in-flight entertainment.", spanish: "Puedes solicitar audífonos para el entretenimiento a bordo." },
{ english: "The seatbelt sign will turn on during landing.", spanish: "La señal de cinturón se encenderá durante el aterrizaje." },
{ english: "Passengers must remain seated until the plane docks.", spanish: "Los pasajeros deben permanecer sentados hasta que el avión esté acoplado." },
{ english: "Baggage claim is located on the lower level.", spanish: "La recogida de equipajes está ubicada en el nivel inferior." },
{ english: "You'll need your passport for international flights.", spanish: "Necesitarás tu pasaporte para vuelos internacionales." },
{ english: "Overhead compartments shouldn't contain heavy items.", spanish: "Los compartimentos superiores no deben contener objetos pesados." },
{ english: "Connecting flights have minimum transfer times.", spanish: "Los vuelos de conexión tienen tiempos mínimos de transferencia." },
{ english: "Delays may occur due to weather conditions.", spanish: "Pueden producirse retrasos debido a condiciones meteorológicas." },
{ english: "Unaccompanied minors require special documentation.", spanish: "Los menores no acompañados requieren documentación especial." },
{ english: "Duty-free shopping is available after security.", spanish: "Las compras libres de impuestos están disponibles después de seguridad." },
{ english: "Priority boarding applies to first class passengers.", spanish: "El embarque prioritario aplica a pasajeros de primera clase." },
{ english: "Luggage weight limits vary by airline.", spanish: "Los límites de peso del equipaje varían según la aerolínea." }, 
{ english: "The end of the world is just the beginning.", spanish: "El fin del mundo es solo el principio." },
 { "english": "Maintain a two-second distance from the vehicle ahead.", "spanish": "Mantén dos segundos de distancia del vehículo adelante." },
  { "english": "Turn on your headlights at dusk or in rain.", "spanish": "Enciende las luces al anochecer o con lluvia." },
  { "english": "Reduce speed when approaching pedestrian crossings.", "spanish": "Reduce la velocidad al acercarte a cruces peatonales." },
  { "english": "Never use your phone while driving.", "spanish": "Nunca uses el teléfono mientras conduces." },
  { "english": "Use the handbrake when parking on slopes.", "spanish": "Usa el freno de mano al estacionar en pendientes." },
  { "english": "Check tire pressure monthly for optimal safety.", "spanish": "Verifica la presión de los neumáticos mensualmente para mayor seguridad." },
  { "english": "Signal at least 30 meters before turning.", "spanish": "Señaliza al menos 30 metros antes de girar." },
  { "english": "Yield to emergency vehicles with sirens on.", "spanish": "Cede el paso a vehículos de emergencia con sirenas activas." },
  { "english": "Stop completely at stop signs, not just slow down.", "spanish": "Detente por completo en señales de alto, no solo reduzcas velocidad." },
  { "english": "You can stay up late as long as you wake up on time tomorrow.", "spanish": "Puedes quedarte despierto hasta tarde siempre que te levantes a tiempo mañana." },
  { "english": "I'll help you as long as you promise to try your best.", "spanish": "Te ayudaré siempre que prometas dar tu mejor esfuerzo." },
  { "english": "This laptop works fine as long as you keep it charged.", "spanish": "Esta laptop funciona bien siempre que la mantengas cargada." },
  { "english": "The beach is beautiful as long as it's not raining.", "spanish": "La playa es hermosa siempre que no esté lloviendo." },
  { "english": "You'll succeed as long as you don't give up.", "spanish": "Tendrás éxito siempre que no te rindas." },
  { "english": "As long as we're together, I'm happy.", "spanish": "Siempre que estemos juntos, soy feliz." },
  { "english": "The soup tastes good as long as you add enough salt.", "spanish": "La sopa sabe bien siempre que le agregues suficiente sal." },
  { "english": "Kids can play here as long as they're supervised.", "spanish": "Los niños pueden jugar aquí siempre que estén supervisados." },
  { "english": "As long as I have my coffee, I can start working.", "spanish": "Siempre que tenga mi café, puedo empezar a trabajar." },
  { "english": "This deal is valid as long as you pay before Friday.", "spanish": "Esta oferta es válida siempre que pagues antes del viernes." },
  { "english": "It took me years to get over you.", "spanish": "Me tomó años superarte." },
{ "english": "She still can't get over you after all this time.", "spanish": "Ella todavía no puede superarte después de todo este tiempo." },
{ "english": "Music helps me get over you.", "spanish": "La música me ayuda a superarte." },
{ "english": "How long will it take to get over you?", "spanish": "¿Cuánto tiempo tomará superarte?" },
{ "english": "I need space to get over you completely.", "spanish": "Necesito espacio para superarte por completo." },
{ "english": "It's just a joke, get over it!", "spanish": "Es solo una broma, ¡supéralo!" },
{ "english": "You lost the game, get over it.", "spanish": "Perdiste el juego, acéptalo." },
{ "english": "Life isn't fair - get over it and move on.", "spanish": "La vida no es justa - acéptalo y sigue adelante." },
{ "english": "He needs to get over his fear of flying.", "spanish": "Él necesita superar su miedo a volar." },
{ "english": "Get over it already, it happened months ago.", "spanish": "Supéralo ya, sucedió hace meses." },
{ "english": "True greatness requires humility.", "spanish": "La verdadera grandeza requiere humildad." },
{ "english": "She accepted the award with genuine humility.", "spanish": "Ella aceptó el premio con genuina humildad." },
{ "english": "Humility is the foundation of wisdom.", "spanish": "La humildad es la base de la sabiduría." },
{ "english": "His humility despite his success is admirable.", "spanish": "Su humildad a pesar de su éxito es admirable." },
{ "english": "Learn to speak with humility and respect.", "spanish": "Aprende a hablar con humildad y respeto." },

  
  {
    "english": "She poured the milk into the cup carefully.",
    "spanish": "Ella vertió la leche en la taza con cuidado."
  },
  {
    "english": "The magician turned the rabbit into a dove.",
    "spanish": "El mago transformó el conejo en una paloma."
  },
  {
    "english": "We need to look into this problem immediately.",
    "spanish": "Necesitamos investigar este problema inmediatamente."
  },
  {
    "english": "He accidentally bumped into the glass door.",
    "spanish": "Él accidentalmente chocó contra la puerta de vidrio."
  },
  {
    "english": "The caterpillar will transform into a butterfly.",
    "spanish": "La oruga se transformará en mariposa."
  },
  {
    "english": "She translated the book into three languages.",
    "spanish": "Ella tradujo el libro a tres idiomas."
  },
  {
    "english": "They broke into the old mansion at midnight.",
    "spanish": "Ellos irrumpieron en la mansión antigua a medianoche."
  },
  {
    "english": "The river flows into the ocean near here.",
    "spanish": "El río desemboca en el océano cerca de aquí."
  },
  {
    "english": "He talked himself into buying the expensive car.",
    "spanish": "Él se convenció a sí mismo de comprar el auto caro."
  },
  {
    "english": "The children jumped into the pool with excitement.",
    "spanish": "Los niños saltaron a la piscina con emoción."
  },


{ english: "The truth will set you free.", spanish: "La verdad te hará libre." },
{ english: "To tell you the truth, I was surprised.", spanish: "A decir verdad, me sorprendió." },
{ english: "There's some truth in what you say.", spanish: "Hay algo de verdad en lo que dices." },
{ english: "He finally revealed the bitter truth.", spanish: "Finalmente reveló la amarga verdad." },
{ english: "In truth, we never expected this outcome.", spanish: "En verdad, nunca esperábamos este resultado." },
{ english: "Seek the truth and you shall find it.", spanish: "Busca la verdad y la encontrarás." },


    ],

    // Include the contractions mapping here
    contractions: {
        "i'm": "i am",
        "you're": "you are",
        "he's": "he is",
        "she's": "she is",
        "it's": "it is",
        "we're": "we are",
        "they're": "they are",
        "i've": "i have",
        "you've": "you have",
        "we've": "we have",
        "they've": "they have",
        "i'll": "i will",
        "you'll": "you will",
        "he'll": "he will",
        "she'll": "she will",
        "it'll": "it will",
        "we'll": "we will",
        "they'll": "they will",
        "isn't": "is not",
        "aren't": "are not",
        "wasn't": "was not",
        "weren't": "were not",
        "hasn't": "has not",
        "haven't": "have not",
        "hadn't": "had not",
        "won't": "will not",
        "wouldn't": "would not",
        "don't": "do not",
        "doesn't": "does not",
        "didn't": "did not",
        "can't": "cannot",
        "couldn't": "could not",
        "shouldn't": "should not",
        "mightn't": "might not",
        "mustn't": "must not",
        "take off": "takeoff",
        "takeoff": "take off"
    },

    obtenerAleatoria: function() {
        return this.phrases[Math.floor(Math.random() * this.phrases.length)];
    }
};
